### ISSUE TITLE
Support mapping BIGINT to string in MySQL

### ISSUE THREAD

**Issue by yshrsmz** [sqlc-dev/sqlc-gen-typescript#15]
Currently sqlc-gen-typescript maps [MySQL's BIGINT type to number type](https://github.com/sqlc-dev/sqlc-gen-typescript/blob/main/src/drivers/mysql2.ts#L16), but the max value of number type is far smaller than that of BIGINT.

`node-mysql2` supports big numbers by converting it to string, so sqlc should also support mapping bigint to string.

https://github.com/mysqljs/mysql#connection-options

Here's a related quote from the doc

> `supportBigNumbers`: When dealing with big numbers (BIGINT and DECIMAL columns) in the database, you should enable this option (Default: `false`).
> `bigNumberStrings`: Enabling both `supportBigNumbers` and `bigNumberStrings` forces big numbers (BIGINT and DECIMAL columns) to be always returned as JavaScript String objects (Default: false). Enabling supportBigNumbers but leaving `bigNumberStrings` disabled will return big numbers as String objects only when they cannot be accurately represented with [JavaScript Number objects] (https://tc39.es/ecma262/#sec-ecmascript-language-types-number-type) (which happens when they exceed the [-2^53, +2^53] range), otherwise they will be returned as Number objects. This option is ignored if `supportBigNumbers` is disabled.

I think we can simply navigate users to enable those two options to use BIGING support.

**Comment by yshrsmz** [comment]
It looks like the PostgreSQL counterpart is already treated as a string.

@kyleconroy Any idea on how we handle this case?
I can send a PR to make this happen.

**Comment by kyleconroy** [comment]
The default types map to the default return values for the `mysql2` library. `mysql2` returns floats for bigints by default, which I think is the wrong choice. Instead, we should allow users to configure this (and a few other options) based on what you can pass to [createPool](https://sidorares.github.io/node-mysql2/docs/examples/connections/create-pool#pooloptions).

```yaml
- schema: "authors/mysql/schema.sql"
  queries: "authors/mysql/query.sql"
  engine: "mysql"
  codegen:
  - plugin: ts
    out: node-mysql2/src/db
    options:
      runtime: node
      driver: mysql2
      mysql2:
        big_number_strings: true
        date_strings: true
```

Do you have time to update #16 with that functionality?
