### ISSUE TITLE
`sqlc generate` error with `go@1.24`

### ISSUE THREAD

**Issue by lumosminima** [sqlc-dev/sqlc-gen-typescript#56]
Using following sqlc.yaml doesn't work with `go@1.24` but downgrading to `go@1.23.6` it generates fine using `sqlc generate`. I use sqlite but have driver set to pg because I can remove the first two imports in generated code and add my own and use the sqlite wasm client. Hacky but it works and there is no other way until improvements suggested in #54
```
version: '2'
plugins:
  - name: ts
    wasm:
      url: https://downloads.sqlc.dev/plugin/sqlc-gen-typescript_0.1.3.wasm
      sha256: 287df8f6cc06377d67ad5ba02c9e0f00c585509881434d15ea8bd9fc751a9368
sql:
  - engine: sqlite
    queries: 'src/sql/queries.sql'
    schema:
      - ../../backend/sql/schema.sql
      - ../../backend/sql/migrations/*
    codegen:
      - out: 'src/lib'
        plugin: ts
        options:
          runtime: node
          driver: pg
```
error:
```
unexpected fault address 0xc015800000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc015800000 pc=0x484f75]

goroutine 7 gp=0xc0002b1180 m=16 mp=0xc000581808 [running]:
runtime.throw({0x1b449d4?, 0x0?})
...
```
